import type { Metadata } from "next";
import { AuthProvider } from "@/context/AuthContext";
import "./globals.css";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import { Toaster } from "react-hot-toast";
import {
  FaFacebook,
  FaInstagram,
  FaLinkedin,
  FaTelegram,
  FaTwitter,
  FaYoutube,
} from "react-icons/fa";
import { Send } from "lucide-react";

export const metadata: Metadata = {
  title: "Trade-Pro",
  description: "Generated by create next app",
};

const Footer = () => (
  <div className="bg-black text-white py-10">
    <div className="container mx-auto px-5 sm:px-6 lg:px-8">
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-8">
        <div>
          <p className="text-sm mb-2">ABCD Tech Park,3rd Floor</p>
          <p className="text-sm mb-2">Abch Road,Banglore</p>
          <p className="text-sm mb-2">Banglore-560103</p>
          <p className="text-sm mb-2">
            <a href="" className="text-blue-500 hover:underline">
              Contact Us
            </a>
          </p>
          <div className="flex flex-wrap gap-4 mt-4">
            <FaFacebook
              className="text-gray-400 hover:text-blue-500 cursor-pointer"
              size={20}
            />
            <FaTwitter
              className="text-gray-400 hover:text-blue-500 cursor-pointer"
              size={20}
            />
            <FaYoutube
              className="text-gray-400 hover:text-blue-500 cursor-pointer"
              size={20}
            />
            <FaInstagram
              className="text-gray-400 hover:text-blue-500 cursor-pointer"
              size={20}
            />
            <FaLinkedin
              className="text-gray-400 hover:text-blue-500 cursor-pointer"
              size={20}
            />
            <Send
              className="text-gray-400 hover:text-blue-500 cursor-pointer"
              size={20}
            />
          </div>
        </div>
        <div>
          <h3 className="font-semibold mb-4 ">Products</h3>
          <ul className="space-y-2">
            {["Stocks", "Futures & Options", "IPO", "Mutal Funds"].map(
              (item) => (
                <li
                  className="text-sm hover:text-blue-500 cursor-pointer"
                  key={item}
                >
                  {item}
                </li>
              )
            )}
          </ul>
        </div>
        <div>
          <h3 className="font-semibold text-lg mb-4"></h3>
          <ul className="space-y-2">
            {["About Us", "Pricing", "Blog", "Carrer", "Help and Support"].map(
              (item) => (
                <li
                  className="text-sm hover:text-blue-500 cursor-pointer"
                  key={item}
                >
                  {item}
                </li>
              )
            )}
          </ul>
        </div>
        <div>
          <h3 className="font-semibold text-lg mb-4"></h3>
          <ul className="space-y-2">
            {[
              "Amc Mutual Funds",
              "Calculators",
              "Glossary",
              "Tradepro Digest",
              "Help and Support",
            ].map((item) => (
              <li
                className="text-sm hover:text-blue-500 cursor-pointer"
                key={item}
              >
                {item}
              </li>
            ))}
          </ul>
        </div>
      </div>
      <div className="mt-8 pt-8 border-t border-gray-700 flex flex-col md:flex-row justify-between items-center gap-4 text-center md:text-left">
        <p className="text-sm text-gray-400 mb-4 md:mb-0">
          {" "}
          © 2016-2024 TradePro. All rights reserved, Built with ❤️ in India
        </p>
      </div>
    </div>
  </div>
);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body
  className={`${GeistSans.variable} ${GeistMono.variable} antialiased overflow-x-hidden bg-gray-900`}
>
  <AuthProvider>
  <Toaster
    position="top-right"
    reverseOrder={false}
    toastOptions={{
      duration: 2500,
      style: {
        background: "#1f2937",
        color: "#fff",
      },
    }}
  />

  <main className="min-h-screen">
    {children}
  </main>

  <Footer />
</AuthProvider>
</body>
    </html>
  );
}